#pragma once

#include <ntddk.h>
#include <wdf.h>
#include <sercx\2.0\Sercx.h>

#include "..\Trace.h"

typedef struct _UART_DEVICE_EXTENSION
{
    WDFDEVICE WdfDevice;
    WDFSPINLOCK WdfDpcSpinLock;
    WDFINTERRUPT WdfInterrupt;
    SERCX2PIOTRANSMIT WdfPioTransmit;
    SERCX2PIORECEIVE WdfPioReceive;
} UART_DEVICE_EXTENSION, *PUART_DEVICE_EXTENSION;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(UART_DEVICE_EXTENSION, GetUartDeviceExtension);

typedef struct _SERCX2_PIO_TRANSMIT_CONTEXT
{
    WDFDEVICE WdfDevice;
} SERCX2_PIO_TRANSMIT_CONTEXT, *PSERCX2_PIO_TRANSMIT_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(SERCX2_PIO_TRANSMIT_CONTEXT, GetSerCx2PioTransmitContext);

typedef struct _SERCX2_PIO_RECEIVE_CONTEXT
{
    WDFDEVICE WdfDevice;
} SERCX2_PIO_RECEIVE_CONTEXT, *PSERCX2_PIO_RECEIVE_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(SERCX2_PIO_RECEIVE_CONTEXT, GetSerCx2PioReceiveContext);

NTSTATUS UartDeviceCreate(_In_ PWDFDEVICE_INIT deviceInit);

EVT_WDF_DEVICE_PREPARE_HARDWARE UartDeviceEvtPrepareHardware;
EVT_WDF_DEVICE_RELEASE_HARDWARE UartDeviceEvtReleaseHardware;
