#pragma once

#include <ntddk.h>
#include <wdf.h>
#include <sercx\2.0\Sercx.h>

#include "CommonDefinitions.h"

BOOLEAN CanReadCharacter(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);
BOOLEAN IsFifoDataLoss(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);

VOID UART_DEVICE_ENABLE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension, _In_ BOOLEAN enable);

USHORT READ_SERIAL_TX_FIFO_SIZE();
USHORT READ_SERIAL_RX_FIFO_SIZE();

VOID FIFO_CONTROL_ENABLE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);

UCHAR LINE_STATUS_READ(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);

UCHAR MODEM_STATUS_READ(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);

VOID LINE_CONTROL_WRITE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension, _In_ UCHAR lineControlValue);

VOID MODEM_CONTROL_WRITE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension, _In_ UCHAR modemControlValue);
VOID MODEM_CONTROL_DISABLE_REQUEST_TO_SEND(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);

VOID DIVISOR_LATCH_WRITE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension, _In_ USHORT divisorValue);

UCHAR RECEIVE_BUFFER_READ(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);

VOID INTERRUPT_DISABLE_ALL(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);
VOID INTERRUPT_ENABLE_LINE_STATUS_CHANGE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);
VOID INTERRUPT_DISABLE_LINE_STATUS_CHANGE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);
VOID INTERRUPT_ENABLE_RECEIVE_DATA_AVAILABLE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);
VOID INTERRUPT_DISABLE_RECEIVE_DATA_AVAILABLE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);
UCHAR INTERRUPT_READ_MASKED_RECEIVE_DATA_AVAILABLE(_In_ PUART_DEVICE_EXTENSION pDeviceExtension);
